### ISSUE TITLE
Enable Repo Discussions

### ISSUE THREAD

**Issue by jacobworrel** [jorshali/snowflake-pool#2]
Can you enable the repo "Discussions" tab? I noticed this repo has no tests yet and I think that would be a better place to discuss this than in "Issues" (along with other things like roadmap etc.). You just have to go to settings, then under Options / Features, there's a checkbox to enable "Discussions".

**Comment by jorshali** [comment]
Discussions have been enabled!  Regarding tests, feel free to add them as you see fit.  As the scope of the project grows, it certainly makes sense to build out a test suite.

Feel free to start a roadmap discussion with any ideas and we can start prioritizing future enhancements.
